### ISSUE TITLE
Check for CHEVERETO_HOSTNAME_PATH

### ISSUE THREAD

**Issue by rodber** [chevereto/docker#10]
> Hello - I'm using the container-builder method of deploying Chevereto.  As part of my deployment, I would like Chevereto to be accessed via a URL path of an existing domain (such as example.com/chevereto).  I have added the CHEVERETO_HOSTNAME_PATH (set to /chevereto/) to the docker environment variables.  This mostly works.  However, when viewing the page, many resources, specially within the lib and app folders, cannot be found resulting in a page that looks like this (page missing resources).

Got this one via Discord, need to check.

**Comment by MikePadge** [comment]
If I'm seeing the same thing here, it's due to mixed http/https content

All of the CSS in Legacy/themes/Peafowl and the JS scripts in there + chevereto.min.js and peafowl.min + the favicons are all requesting from http but attempting to server over HTTPS. 

This could be something with my reverse proxy headers as well, I'm using traefik.

**Comment by rodber** [comment]
> If I'm seeing the same thing here, it's due to mixed http/https content

Is not the same issue, the hostname path is useless in Docker context here as theres no binding, the system is at `/` which is not configurable at this time.

> All of the CSS in Legacy/themes/Peafowl and the JS scripts in there + chevereto.min.js and peafowl.min + the favicons are all requesting from http but attempting to server over HTTPS. 

The HTTPS support is also not implemented in this context. If you want https you will require to either setup certs at Docker layer or proxy on top of the server. 

> This could be something with my reverse proxy headers as well, I'm using traefik. 

You can control the environment variables to tweak https.

https://v4-docs.chevereto.com/application/configuration/environment.html
