### ISSUE TITLE
prodlem has raise

### ISSUE THREAD

**Issue by Aronlele** [Chevereto/docker#15]
![image](https://user-images.githubusercontent.com/7881859/121036611-6f12bc80-c7e1-11eb-8ec6-69e239480f5c.png)

**Comment by rodber** [comment]
Shell showoff? Mine is prettier.

![image](https://user-images.githubusercontent.com/20590102/121037882-d39c3000-c77d-11eb-95aa-52e71a948db0.png)

(by the way, I don't know how to debug your issue)
