### ISSUE TITLE
Add video guide

### ISSUE THREAD

**Issue by rodber** [chevereto/docker#19]
This project need a video guide to show users how this should be used. Also, it needs some non-technical explanations and recommendations on third party Docker management software that could be used.

**Comment by MikePadge** [comment]
What I did:

Forked the v4-docker-production repo and pulled into a private repo
Pulled locally and edited:
- Makefile
I haven't gotten my stupid docker context switch working on a few of my old testing environements. I need a punch of kernel updates anyway, so I just patched adding the hyphen to the docker-compose calls. Most people shouldn't have to do this. I'm being lazy.

Changed PROTOCOL to https on line 5
Changed NAMESPACE to my FQDN including subdomain (not sure if this is correct) on line 7
Changed tag_basename to my private gitlab server

added an up-df make command with --force-recreate on the docker-compose call

- php.Dockerfile
changed CHEVERETO_HTTPS to true on line 58

changed CHEVERETO_HOSTNAME to my fqdn + subdomain on line 57
increased max filesize, post size, and memory limit

- projects/prod.yml
added CHEVERETO_HTTPS: true on line 52
changed CHEVERETO_ASSET_STORAGE_URL to https on line 54 
~~~~~~
Committed changes and pushed to private repo.

Ran make image + entered license key

Pushed the images to the private repo

Ran make up-d on the Chevereto VM server I have

Setup traefik as a reverse proxy for it
Traefik handles the certificate signing. I use a wildcard that I bought, but I also have a Let's Encrypt config here as well. 

Traefik can run directly on the same host as chevereto, but Caddy would probably be easier to implement into a docker-compose to bundle with Chevereto to handle certificates.

**Comment by rodber** [comment]
This project doesn't handle https, there's an ongoing issue #17 for it. These https env vars are for just outputting URLs with https, the actual cert is not provided. I don't know yet the best way to provide that for this context.

**Comment by MikePadge** [comment]
I got it working with Traefik and HTTPS, I had some docker cache leftover that I was missing an env var for https, so I was loading mixed content. 

Traefik is terminating SSL and passing http back to Chevereto... I did not look at the NGINX config at all, and it seems to be fine... but I need to go back and check my traefik config against nginx when I get a chance.
