### ISSUE TITLE
Provide shell script for automated process

### ISSUE THREAD

**Issue by rodber** [Chevereto/docker#2]
Provide a `shell` that does all the manual labor.

- Provides the Installer
- Query installer directly (php installer.php args)

**Comment by rodolfoberrios** [comment]
Hi @MikePadge, no offense taken in the names you use, that's up to you. Many other users also refers to Chevereto as "Chevy" which sounds nice.

I will add Docker compose instructions in the readme.

Many thanks for sharing!
