### ISSUE TITLE
 RecursiveDirectoryIterator::__construct(/var/www/html/app/install/update/temp/-/): failed to open dir: No such file or directory

### ISSUE THREAD

**Issue by ech1** [chevereto/docker#34]
RecursiveDirectoryIterator::__construct(/var/www/html/app/install/update/temp/-/): failed to open dir: No such file or directory

![image](https://user-images.githubusercontent.com/49315644/147373916-7423d075-23cb-4837-b23a-29c56e0a9331.png)

**Comment by rodber** [comment]
This is the repo for Chevereto Docker bootstrap provisioning. You are using Chevereto-Free so open an issue at [rodber/chevereto-free](https://github.com/rodber/chevereto-free)
